# based on https://github.com/ionelmc/python-hunter/blob/master/.travis.yml

language: python
sudo: false
branches:
  only:
    - master
    - /^\d\.\d+$/
    - /^\d\.\d+\.\d+(rc\d+|\.dev\d+)?$/
matrix:
  include:
    - python: '3.6'
      env:
        - TOXENV=py36-pure-cover
    - python: '3.6'
      env:
        - TOXENV=py36-pure-nocov
    - python: '3.6'
      env:
        - TOXENV=py36-cython-cover
    - python: '3.6'
      env:
        - TOXENV=py36-cython-nocov
install:
    - |
      if [ "$TOXENV" = "pypy" ]; then
        export PYPY_VERSION="pypy-6.0.0-linux_x86_64-portable"
        wget "https://bitbucket.org/squeaky/portable-pypy/downloads/${PYPY_VERSION}.tar.bz2"
        tar -jxf ${PYPY_VERSION}.tar.bz2
        virtualenv --python="$PYPY_VERSION/bin/pypy" "$HOME/virtualenvs/$PYPY_VERSION"
        source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
      fi
      if [ "$TOXENV" = "pypy3" ]; then
        export PYPY_VERSION="pypy3.5-5.9-beta-linux_x86_64-portable"
        wget "https://bitbucket.org/squeaky/portable-pypy/downloads/${PYPY_VERSION}.tar.bz2"
        tar -jxf ${PYPY_VERSION}.tar.bz2
        virtualenv --python="$PYPY_VERSION/bin/pypy3" "$HOME/virtualenvs/$PYPY_VERSION"
        source "$HOME/virtualenvs/$PYPY_VERSION/bin/activate"
      fi
    - pip install -U pip tox Cython codecov
script:
    - tox
after_success:
    - codecov
