language: python
sudo: false
branches:
  only:
    - master
    - /^\d\.\d+$/
    - /^\d\.\d+\.\d+(rc\d+|\.dev\d+)?$/
matrix:
  include:
    - python: 2.7
      env: TOXENV=py27
    - python: 3.3
      env: TOXENV=py33
    - python: 3.4
      env: TOXENV=py34
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
install:
    - pip install -U pip tox Cython codecov
script:
    - tox
after_success:
    - codecov
